# docker-compose config for local development
version: '3'
services:
  frontend:
    container_name: neutrino-frontend-local
    command: yarn dev
    build:
      context: ./
      dockerfile: deployment/dockerfiles/Dockerfile.frontend.local
    volumes:
      - ./frontend:/frontend
    expose:
      - 3020
    ports:
      - 3020:3020
    env_file:
      - .env
      - .env.frontend

#  backend:
#    container_name: neutrino-backend-local
#    command: uvicorn main:app --host 0.0.0.0 --port 4020 --loop 'uvloop' --lifespan on --reload --proxy-headers
#    build:
#      context: ./
#      dockerfile: deployment/dockerfiles/Dockerfile.backend.local
#    volumes:
#      - ./backend:/backend
#    depends_on:
#      - db
#    expose:
#      - 4020
#    ports:
#      - 4020:4020
#    env_file:
#      - .env
#      - .env.backend
#
#  scheduler:
#    container_name: neutrino-scheduler-local
#    command: python start_scheduler.py --log=INFO
#    build:
#      context: ./
#      dockerfile: deployment/dockerfiles/Dockerfile.backend.local
#    volumes:
#      - ./backend:/backend
#    depends_on:
#      - db
#    env_file:
#      - .env
#      - .env.backend
#
#  db:
#    container_name: neutrino-mongodb-local
#    image: mongo:4.2-bionic
#    command: mongod --port 27017
#    ports:
#      - 27017:27017
#    env_file:
#      - .env
#      - .env.db
