version: '3'
services:
  frontend:
    container_name: schutz-frontend
    restart: always
    command: yarn start
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/frontend:develop-latest
    expose:
      - 3020
    ports:
      - 3020:3020
    env_file:
      - .env
      - .env.frontend


#  backend:
#    container_name: schutz-backend
#    restart: always
#    command: uvicorn main:app --host 0.0.0.0 --port 4020 --loop 'uvloop' --lifespan on --proxy-headers
#    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/backend:develop-latest
#    depends_on:
#      - db
#    expose:
#      - 4020
#    ports:
#      - 4020:4020
#    env_file:
#      - .env
#      - .env.backend


#  scheduler:
#    container_name: schutz-scheduler
#    restart: always
#    command: python start_scheduler.py --log=INFO
#    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/backend:develop-latest
#    depends_on:
#      - db
#    env_file:
#      - .env
#      - .env.backend
#
#
#  db:
#    container_name: schutz-mongodb
#    restart: always
#    image: mongo:4.2-bionic
#    command: mongod --port 27020 --auth
#    ports:
#      - 27020:27020
#    env_file:
#      - .env
#      - .env.db
