# docker-compose config for local development
version: '3'
services:
  frontend:
    container_name: neutrino-frontend-local
    command: yarn dev
    build:
      context: ./
      dockerfile: deployment/dockerfiles/Dockerfile.frontend.local
    volumes:
      - ./frontend:/frontend
    expose:
      - 3020
    ports:
      - 3020:3020
    env_file:
      - .env
      - .env.frontend
