FROM node:13.8-buster

ENV DEBUG=False
ENV ENV=production
ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3020
ENV API_URL=https://my.nts.fund/api
ENV API_URL_BROWSER=https://my.nts.fund/api
ENV SENTRY_DSN=https://ce48edd71b494b9f870ae411b73a1097@sentry.elastoo.com/20

COPY ./frontend/ /frontend/
WORKDIR /frontend/

# Install Yarn if it is not installed
RUN yarn -v || npm install -g yarn

# Install requirements
RUN yarn install && yarn build
